"""
custody_calculator.py - Compute day-by-day custody intervals.
Inputs: custody_rules.json + standard_calendar.json
Output: custody_intervals.json (array of {start, end, custodian, reason})

All rules derived from custody_rules.json (which comes from statute JSON).
No hard-coded assumptions.
"""
import json
import os
import sys
import calendar as calmod
from datetime import date, timedelta
from dataclasses import dataclass
from typing import Literal

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))


@dataclass
class Interval:
    start: date
    end: date
    custodian: Literal["dad", "mom"]
    reason: str

    def to_dict(self) -> dict:
        return {
            "start": str(self.start),
            "end": str(self.end),
            "custodian": self.custodian,
            "reason": self.reason,
        }


class CustodyCalculator:
    """
    Computes custody intervals for all school years.
    Reads rules from custody_rules.json (generated by rule_builder.py).
    Reads school calendar from standard_calendar.json.
    """

    def __init__(self, rules: dict, calendar_data: dict):
        self.rules = rules
        self.cal = calendar_data
        self.school_years = calendar_data.get("schoolYears", [])

    # ─── Static helpers ──────────────────────────────────────────────────────

    @staticmethod
    def _nth_weekday(year: int, month: int, weekday: int, n: int) -> date:
        """Nth occurrence of weekday in month. weekday: 0=Mon, 6=Sun."""
        c = calmod.Calendar()
        occurrences = [day for day in c.itermonthdays2(year, month)
                       if day[0] != 0 and day[1] == weekday]
        if n - 1 < len(occurrences):
            return date(year, month, occurrences[n - 1][0])
        return None

    @staticmethod
    def _fathers_day(year: int) -> date:
        """Third Sunday of June."""
        return CustodyCalculator._nth_weekday(year, 6, 6, 3)

    @staticmethod
    def _mothers_day(year: int) -> date:
        """Second Sunday of May."""
        return CustodyCalculator._nth_weekday(year, 5, 6, 2)

    @staticmethod
    def _all_fridays(year: int, month: int) -> list:
        """All Fridays in the given month."""
        c = calmod.Calendar()
        return sorted([
            date(year, month, day[0])
            for day in c.itermonthdays2(year, month)
            if day[0] != 0 and day[1] == 4
        ])

    def _is_noschool_day(self, d: date) -> bool:
        """Return True if d is a no-school day for students.
        Checks both standalone noschool_days AND days within school breaks."""
        for sy in self.school_years:
            sy_start = date.fromisoformat(sy["start"])
            sy_end = date.fromisoformat(sy["end"])
            if not (sy_start <= d <= sy_end):
                continue
            # Check standalone noschool days
            noschool = {date.fromisoformat(n["date"]) for n in sy.get("noschool_days", [])}
            if d in noschool:
                return True
            # Check if d is inside a school break (students off during break)
            for br_name, br in sy.get("breaks", {}).items():
                br_start = date.fromisoformat(br["start"])
                br_end = date.fromisoformat(br["end"])
                if br_start <= d <= br_end:
                    return True
        return False

    # ─── Break detection ─────────────────────────────────────────────────────

    def _in_which_break(self, d: date) -> tuple:
        """
        Return (break_name, break_data) or (None, None).
        Checks ALL breaks in all school years regardless of the school year date range.
        Also handles pre-school summer gaps: May 22 through the day before
        each school year starts (Aug 13-17 for 2025-2026) - kids not yet in
        school, so treated as summer for custody purposes.
        """
        for sy in self.school_years:
            for br_name, br in sy.get("breaks", {}).items():
                br_start = date.fromisoformat(br["start"])
                br_end_raw = date.fromisoformat(br["end"])
                # Per TX §153.314: holiday possession ends "the day before school resumes"
                # (same as Christmas clause 2). For spring break, extend BOTH ends:
                # - End: Sunday before school resumes (Mar 22 for 2025-2026)
                # - Start: last school day before break (Mar 13 for 2025-2026)
                # Days before the district break start (Mar 14-15) get reason
                # "spring_break_pre" so they don't merge with the Mom district period.
                if br_name == "spring":
                    resume_candidate = br_end_raw + timedelta(days=1)
                    days_until_monday = (7 - resume_candidate.weekday()) % 7
                    school_resume = resume_candidate + timedelta(days=days_until_monday)
                    br_end_extended = school_resume - timedelta(days=1)
                    br_start_extended = self._last_school_day_before_break(br_name, sy)
                    if br_start_extended is None:
                        br_start_extended = br_start
                else:
                    br_end_extended = br_end_raw
                    br_start_extended = br_start
                if br_start_extended <= d <= br_end_extended:
                    effective_br_name = "summer" if br_name == "summer_pre_school" else br_name
                    br_data = dict(br)
                    br_data["end"] = br_end_extended.isoformat()
                    # For spring break, tag pre/post district days with distinct names so
                    # they don't merge with the main (district) spring break period.
                    if br_name == "spring":
                        if d < br_start:
                            effective_br_name = "spring_break_pre"
                        elif d > br_end_raw:
                            effective_br_name = "spring_break_post"
                    return effective_br_name, br_data

        # Pre-school summer gap: May 22 through the day before school year starts.
        # Kids aren't in school yet = summer (mom).
        for sy in self.school_years:
            sy_start = date.fromisoformat(sy["start"])
            # If school starts Aug or Sep, the pre-school summer is May 22-Aug (start-1).
            # This only applies within a single calendar year May-Aug window.
            if sy_start.month not in (8, 9):
                continue
            # effective_summer covers May 22 through (sy_start - 1 day)
            effective_summer_end = sy_start - timedelta(days=1)
            if effective_summer_end.month not in (7, 8):
                continue
            # Check: is d between May 22 and (sy_start - 1) of the calendar year
            # that sy_start falls in? If so, it's pre-school summer (mom).
            summer_start_of_year = date(sy_start.year, 5, 22)
            if not (summer_start_of_year <= d < sy_start):
                continue
            if "summer" in sy.get("breaks", {}):
                return "summer", sy["breaks"]["summer"]
            return "summer", {
                "start": summer_start_of_year.isoformat(),
                "end": effective_summer_end.isoformat()
            }

        # Post-school-year summer gap: May 22-Aug 17 of the NEXT calendar year after
        # a school year ends, when there is no school.  Only applies to dates OUTSIDE
        # all school year ranges (e.g. Jul 2027, which falls after May 2027 SY end).
        # If d is inside a school year (first loop already covered breaks there), skip.
        for sy in self.school_years:
            sy_start = date.fromisoformat(sy["start"])
            sy_end = date.fromisoformat(sy["end"])
            if sy_start <= d <= sy_end:
                return None, None  # d is a school day; first loop handled breaks

        for sy in self.school_years:
            if "summer" not in sy.get("breaks", {}):
                continue
            br = sy["breaks"]["summer"]
            br_start = date.fromisoformat(br["start"])
            if br_start.month == 5 and br_start.day == 22:  # valid summer anchor
                # Match if d is in the May 22-Aug 17 window but beyond the
                # br_end year (e.g. Jul 2027 with br covering May-Aug 2026).
                # May: day >= 22 only; Jun-Jul: any day; Aug: day <= 17 only.
                in_window = (
                    (d.month == 5 and d.day >= 22) or
                    (d.month in (6, 7)) or
                    (d.month == 8 and d.day <= 17)
                )
                if in_window:
                    return "summer", br

        return None, None

    def _break_custodian(
        self, break_name: str, break_data: dict, d: date, is_odd_year: bool
    ) -> tuple:
        """
        Determine custodian for a day within a break.
        """
        rules = self.rules
        br_start = date.fromisoformat(break_data["start"])

        if break_name == "thanksgiving":
            parent = rules["holidays"]["thanksgiving"]["odd_year" if is_odd_year else "even_year"]
            return parent, "thanksgiving"

        elif break_name == "christmas":
            # Per §153.314(1)-(2):
            # Split at noon on December 28.
            # First half: 6pm on dismissal day → noon Dec 28 (date = Dec 27)
            # Second half: noon Dec 28 → day before school resumes
            # Even year: possessory(Dad) first half, Managing(Mom) second half
            # Odd year: Managing(Mom) first half, Possessory(Dad) second half
            # Rules file stores first-half parent per year parity; second half is the other parent.
            # First half: Dec 18-27 (before noon Dec 28)
            # Second half: Dec 28-Jan 4 (on or after Dec 28)
            # Split at noon Dec 28. First half = dates before Dec 28;
            # second half = Dec 28 and after (through day before school resumes).
            # Handle year-boundary: Jan dates are always second half (after noon Dec 28).
            # For Dec dates: before Dec 28 = first half, Dec 28+ = second half.
            # Per statute: alternation is based on "calendar year in which the
            # Christmas vacation begins" (br_start.year), NOT the date d.year.
            # Split at noon Dec 28:
            #   First half: Dec 18-27  (morning before noon)
            #   Second half: Dec 28+   (noon onward, including all Jan dates)
            # First half: Dec 18-28 (up to and including Dec 28 before noon)
            # Second half: Dec 28 noon onward + all Jan dates
            # Split at noon Dec 28. Dec 28 belongs to FIRST half (before noon).
            is_first_half = d.month == 12 and d.day <= 28
            is_odd_year_br = br_start.year % 2 == 1
            yr_key = "odd_year" if is_odd_year_br else "even_year"
            first_half_parent = rules["holidays"]["christmas"][f"{yr_key}_first"]
            parent = first_half_parent if is_first_half else ("dad" if first_half_parent == "mom" else "mom")
            reason = "christmas_first_half" if is_first_half else "christmas_second_half"
            return parent, reason

        elif break_name == "spring":
            parent = rules["holidays"]["spring_break"]["odd_year" if is_odd_year else "even_year"]
            return parent, "spring_break"

        elif break_name in ("spring_break_pre", "spring_break_post"):
            # Extended spring break days: Sat/Sun before (pre) or after (post) district break.
            # Use same odd/even year rule as regular spring break.
            parent = rules["holidays"]["spring_break"]["odd_year" if is_odd_year else "even_year"]
            return parent, break_name

        elif break_name == "summer":
            # Dad gets July 1-30; all other summer days are mom
            dad_start = date(d.year, 7, 1)
            dad_end = date(d.year, 7, 30)
            if dad_start <= d <= dad_end:
                return rules["summer"]["possessory_parent"], "summer_possessory"
            else:
                return rules["summer"]["remainder_parent"], "summer_remainder"

        # Unknown break type → mom
        return rules["parents"]["managing"], break_name

    # ─── Main logic ──────────────────────────────────────────────────────────

    def _get_custodian(self, d: date) -> tuple:
        """
        Determine custodian for a single date.
        Priority order (per §153.314):
          1. Parents day - checked FIRST, overrides everything
          2. Last school day BEFORE a break = that break day 1
          3. School breaks (thanksgiving, christmas, spring, summer)
          4. Extended Weekend Rule: if Thu is dad's, Fri-Sat-Sun also belong to dad
          5. Regular school day Thu / 1st-3rd-5th Fri rules
          6. Fallback: managing conservator (mom)
        """
        rules = self.rules
        is_odd_year = d.year % 2 == 1

        # 1. Parents day
        fd = self._fathers_day(d.year)
        if fd:
            fri_before_fd = fd - timedelta(days=2)
            if fri_before_fd <= d <= fd:
                return rules["fathers_day"]["parent"], "fathers_day"

        md = self._mothers_day(d.year)
        if md:
            fri_before_md = md - timedelta(days=2)
            if fri_before_md <= d <= md:
                return rules["mothers_day"]["parent"], "mothers_day"

        # 2. Special: last school day BEFORE a break = that break day 1
        # Check each break; if d is the last school day before it starts, it's break day 1
        for sy in self.school_years:
            for br_name, br in sy.get("breaks", {}).items():
                br_start = date.fromisoformat(br["start"])
                # Walk backward from br_start-1 to find last school day
                prev = br_start - timedelta(days=1)
                for _ in range(90):
                    if prev.weekday() < 5:  # Mon-Fri
                        noschool = {date.fromisoformat(n["date"]) for n in sy.get("noschool_days", [])}
                        if prev in noschool:
                            prev -= timedelta(days=1)
                            continue
                        # Not in another break?
                        in_other = any(
                            date.fromisoformat(b2["start"]) <= prev <= date.fromisoformat(b2["end"])
                            for n2, b2 in sy.get("breaks", {}).items()
                            if n2 != br_name
                        )
                        if not in_other:
                            break
                        prev -= timedelta(days=1)
                    else:
                        prev -= timedelta(days=1)
                else:
                    prev = br_start - timedelta(days=1)

                if d == prev:
                    # d is the last school day before this break - it's break day 1
                    br_data = {"start": br["start"], "end": br["end"], "label": br.get("label", {})}
                    return self._break_custodian(br_name, br_data, d, is_odd_year)

        # 3. School breaks (normal case)
        break_name, break_data = self._in_which_break(d)
        if break_name:
            return self._break_custodian(break_name, break_data, d, is_odd_year)

        # 3b. No-school day rollover (per §153.312): after all break checks pass,
        # a no-school day inherits the custodian of the preceding day (which may
        # itself be a no-school day — walk backward until we reach an actual school
        # day, then use that day's custodian with reason "no_school_day").
        if self._is_noschool_day(d):
            prev = d - timedelta(days=1)
            for _ in range(30):
                if not self._is_noschool_day(prev):
                    underlying_cust, _ = self._get_custodian(prev)
                    return underlying_cust, "no_school_day"
                prev -= timedelta(days=1)

        # 2b. Thanksgiving: last school day BEFORE Thanksgiving = Thanksgiving day 1
        # Per §153.314(3): possession begins the day school is dismissed BEFORE Thanksgiving.
        # This is SEPARATE from normal breaks because Thanksgiving is a noschool_day period,
        # not a formal "break" in the calendar data.
        tg_start, tg_end = self._thanksgiving_period(d)
        if tg_start is not None:
            if d == tg_start:
                parent = rules["holidays"]["thanksgiving"]["odd_year" if is_odd_year else "even_year"]
                return parent, "thanksgiving"

        # 3b. Thanksgiving days within the period (last school day → Sunday after)
        if tg_start is not None and tg_start < d <= tg_end:
            parent = rules["holidays"]["thanksgiving"]["odd_year" if is_odd_year else "even_year"]
            return parent, "thanksgiving"

        # 4. Extended Weekend Rule (per §153.314(e))
        # Only applies on 1st/3rd/5th Fridays - the "weekend" belongs to dad,
        # and the Thu overnight extends to cover Fri-Sat-Sun as one block.
        # BUT: if today is a qualifying Fri, Sat, or Sun, and the underlying
        # custodian/reason (without extended weekend) is a break day (e.g.
        # "thanksgiving", "christmas_first_half"), skip this step — the break
        # custodian rules take precedence.
        if d.weekday() == 4:  # Friday
            fridays = sorted(self._all_fridays(d.year, d.month))
            if d in fridays:
                fri_rank = fridays.index(d) + 1
                if fri_rank in [1, 3, 5]:
                    underlying_cust, underlying_reason = self._no_extended_weekend(d)
                    if underlying_reason not in ("weekend", "thursday"):
                        pass  # d is a break day (e.g. "thanksgiving") — skip dad weekend
                    else:
                        return "dad", "weekend"

        if d.weekday() in (5, 6):  # Saturday or Sunday
            fri = d - timedelta(days=d.weekday() - 4)  # preceding Friday
            fridays = sorted(self._all_fridays(fri.year, fri.month))
            if fri in fridays:
                fri_rank = fridays.index(fri) + 1
                if fri_rank in [1, 3, 5]:
                    fri_underlying_cust, fri_underlying_reason = self._no_extended_weekend(fri)
                    if fri_underlying_reason not in ("weekend", "thursday"):
                        pass  # Fri was a break day — skip dad weekend extension
                    else:
                        return "dad", "weekend"

        # 4b. Non-qualifying Friday no-school day (per §153.312)
        # If Thu was a school day (Dad's) and Fri is a no-school day,
        # "school dismissal Friday" never occurred — Dad's possession rolls forward.
        # Extended through the weekend until school resumes.
        if d.weekday() == 4:  # Friday no-school
            thu = d - timedelta(days=1)  # preceding Thursday
            fri_is_ns = self._is_noschool_day(d)
            thu_was_school = thu.weekday() == 3 and not self._is_noschool_day(thu)
            if fri_is_ns and thu_was_school:
                # Dad had Thu school day; Fri no-school — possession rolls forward
                # BUT: if Thu was itself the last school day before a break (Step 2),
                # Thu already belongs to the break period; don't double-extend into Fri.
                thu_is_last_school_day = self._is_last_school_day_before_any_break(thu)
                if thu_is_last_school_day:
                    pass  # skip — Thu already assigned to break, not Dad's Thu possession
                else:
                    return "dad", "no_school_day"

        # 4c. Weekend extension for Dad's no-school Friday
        # After a qualifying Fri no-school (step 4) OR non-qualifying Fri no-school (step 4b),
        # Sat-Sun-Mon belong to Dad until school resumes.
        if d.weekday() in (5, 6):  # Saturday or Sunday
            fri = d - timedelta(days=d.weekday() - 4)  # preceding Friday
            if self._is_noschool_day(fri):
                # Preceding Fri was a no-school day — Dad's possession extended
                # BUT: only if Fri was a normal school day with Dad's standard weekend/Thu,
                # NOT if Fri was already the last school day before a break (Step 2).
                # When Fri is the last school day before a break, Step 2 already assigns
                # it to the break period — Dad's weekend should not叠加 on top.
                # Skip only if Fri was the last school day before a break (Step 2 case).
                # In that case, the break custodian rules already cover the weekend.
                # Standalone no-school days (like a one-off student holiday) still extend.
                if self._is_last_school_day_before_any_break(fri):
                    pass  # Fri is a break day 1 — don't double-extend
                else:
                    return "dad", "no_school_day"

        # 4d. Monday no-school extends Dad's weekend
        # Per §153.312: if weekend coincides with a holiday (no-school Mon),
        # possession ends at 6 p.m. on the holiday.
        # If the preceding Fri was a qualifying dad weekend (step 4),
        # and Mon is no-school, Dad extends through Mon.
        if d.weekday() == 0:  # Monday
            fri = d - timedelta(days=3)  # preceding Friday
            fridays = sorted(self._all_fridays(fri.year, fri.month))
            if fri in fridays:
                fri_rank = fridays.index(fri) + 1
                was_dad_weekend = fri_rank in [1, 3, 5]
            else:
                was_dad_weekend = False
            was_noschool_fri = self._is_noschool_day(fri)
            if (was_dad_weekend or was_noschool_fri) and self._is_noschool_day(d):
                # Dad's weekend extends through Mon no-school day
                return "dad", "no_school_day"

        # 5. Regular school day rules: Thursday + 1st-3rd-5th Friday
        if d.weekday() == 3:  # Thursday
            return rules["thursday"]["parent"], "thursday"

        if d.weekday() == 4:  # Friday
            fridays = sorted(self._all_fridays(d.year, d.month))
            if d in fridays:
                fri_rank = fridays.index(d) + 1
                if fri_rank in [1, 3, 5]:
                    return rules["weekend"]["parent"], "weekend"

        # 6. Fallback: managing conservator (mom)
        return rules["parents"]["managing"], "default_custody"

    def _no_extended_weekend(self, d: date) -> tuple:
        """
        Internal custodian check that does NOT apply the extended weekend rule.
        Used only by the extended weekend check to avoid infinite recursion.
        """
        rules = self.rules
        is_odd_year = d.year % 2 == 1
        fd = self._fathers_day(d.year)
        if fd:
            fri_before_fd = fd - timedelta(days=2)
            if fri_before_fd <= d <= fd:
                return rules["fathers_day"]["parent"], "fathers_day"
        md = self._mothers_day(d.year)
        if md:
            fri_before_md = md - timedelta(days=2)
            if fri_before_md <= d <= md:
                return rules["mothers_day"]["parent"], "mothers_day"
        # Step 2 (no_extended version): last school day before a break = that break day 1
        for sy in self.school_years:
            for br_name, br in sy.get("breaks", {}).items():
                last_sd = self._last_school_day_before_break(br_name, sy)
                if last_sd and d == last_sd:
                    br_data = {"start": br["start"], "end": br["end"], "label": br.get("label", {})}
                    return self._break_custodian(br_name, br_data, d, is_odd_year)
        break_name, break_data = self._in_which_break(d)
        if break_name:
            return self._break_custodian(break_name, break_data, d, is_odd_year)
        if d.weekday() == 3:
            return rules["thursday"]["parent"], "thursday"
        if d.weekday() == 4:
            fridays = sorted(self._all_fridays(d.year, d.month))
            if d in fridays:
                fri_rank = fridays.index(d) + 1
                if fri_rank in [1, 3, 5]:
                    return rules["weekend"]["parent"], "weekend"
        return rules["parents"]["managing"], "default_custody"

    def _last_school_day_before_break(self, break_name: str, sy=None):
        """
        Return the last actual school day BEFORE a break starts.
        This day belongs to the break, not to regular custody.
        e.g. Dec 18 (last day before Christmas) = Christmas day 1
             May 21 (last day before summer) = summer day 1

        If sy is provided, only search within that school year.
        Otherwise search all school years (returns the last match found).
        """
        school_years_to_search = [sy] if sy else self.school_years
        for sy_iter in school_years_to_search:
            br = sy_iter.get("breaks", {}).get(break_name)
            if not br:
                continue
            br_start = date.fromisoformat(br["start"])
            noschool = {date.fromisoformat(n["date"]) for n in sy_iter.get("noschool_days", [])}
            prev = br_start - timedelta(days=1)
            for _ in range(90):
                if prev.weekday() < 5 and prev not in noschool:
                    in_other = any(
                        s <= prev <= e
                        for name, b in sy_iter.get("breaks", {}).items()
                        if name != break_name
                        for s, e in [(date.fromisoformat(b["start"]), date.fromisoformat(b["end"]))]
                    )
                    if not in_other:
                        return prev
                prev -= timedelta(days=1)
            return None
        return None


    def _is_last_school_day_before_any_break(self, d: date) -> bool:
        """
        Return True if d is the last school day before ANY school break.
        Used to prevent double-extension when a day is already claimed by Step 2.
        """
        for sy in self.school_years:
            for br_name in sy.get("breaks", {}).keys():
                last_sd = self._last_school_day_before_break(br_name, sy)
                if last_sd and d == last_sd:
                    return True
        return False

    # ─── Thanksgiving helper ─────────────────────────────────────────────────
    # Per §153.314(3): Period begins at the time school is dismissed on the day
    # BEFORE Thanksgiving, and ends 6pm on the Sunday after Thanksgiving.

    def _thanksgiving_period(self, d: date) -> tuple:
        """
        Return (start_date, end_date) of the Thanksgiving period for date d,
        or (None, None) if d is not in any Thanksgiving period.
        Per §153.314(3): start = last school day before the Thanksgiving break,
        end = the day before school resumes after Thanksgiving (Sunday after).
        """
        for sy in self.school_years:
            sy_start = date.fromisoformat(sy["start"])
            sy_end = date.fromisoformat(sy["end"])

            # Find the Thanksgiving "break" period in this school year.
            # The breaks dict has a 'thanksgiving' key with start/end dates.
            tg_break = sy.get("breaks", {}).get("thanksgiving")
            if not tg_break:
                continue
            tg_break_start = date.fromisoformat(tg_break["start"])
            tg_break_end = date.fromisoformat(tg_break["end"])

            # Walk backward from tg_break_start-1 to find the last school day
            # BEFORE the break (this is "the day school is dismissed before Thanksgiving").
            prev = tg_break_start - timedelta(days=1)
            noschool = {date.fromisoformat(n["date"]) for n in sy.get("noschool_days", [])}
            for _ in range(90):
                if prev.weekday() < 5 and prev not in noschool:
                    in_other = any(
                        date.fromisoformat(b2["start"]) <= prev <= date.fromisoformat(b2["end"])
                        for n2, b2 in sy.get("breaks", {}).items()
                    )
                    if not in_other:
                        break
                prev -= timedelta(days=1)
            else:
                prev = tg_break_start - timedelta(days=1)

            tg_period_start = prev  # last school day before Thanksgiving break

            # tg_period_end: Sunday after Thanksgiving.
            # Use the actual Thanksgiving noschool_day (the Thursday) if found;
            # otherwise derive from tg_break_start (Friday before the break week).
            # For 2026-2027: tg_break_start=Nov21 (Fri), so Thanksgiving=Nov21+5=Nov26 (Thu).
            # Sunday after Nov26 = Nov29. Sunday after Nov21 = Nov22.
            # Use the Thanksgiving day itself (Nov26) not the break start (Nov21).
            thanksgiving_day = None
            for nsd in sy.get("noschool_days", []):
                nsd_date = date.fromisoformat(nsd["date"])
                label_text = nsd.get("label", {})
                if isinstance(label_text, dict):
                    label_text = label_text.get("en", "")
                if "thanksgiving" in label_text.lower() and nsd_date.weekday() == 3:
                    thanksgiving_day = nsd_date
                    break
            # Fallback: Thanksgiving is 5 days after tg_break_start (Fri -> Thu)
            if thanksgiving_day is None:
                thanksgiving_day = tg_break_start + timedelta(days=5)

            # Sunday after Thanksgiving: next Sunday = today + ((6-weekday) % 7), +7 if today is Sunday
            days_until_sunday = (6 - thanksgiving_day.weekday()) % 7
            if days_until_sunday == 0:
                days_until_sunday = 7
            tg_period_end = thanksgiving_day + timedelta(days=days_until_sunday)
            # Extend to cover no-school days between Sunday and school resuming.
            tg_period_end = max(tg_period_end, tg_break_end)

            # Check if d is in the statute Thanksgiving period
            if tg_period_start <= d <= tg_period_end:
                return tg_period_start, tg_period_end

        return None, None

    # ─── Compute all intervals ───────────────────────────────────────────────

    def compute_intervals(self) -> list:
        """
        Compute custody intervals for ALL calendar days from earliest school year
        start through latest school year end, PLUS the summer break that follows
        the last school year (covers July-August after the final SY ends).
        This ensures summer breaks between and across school years are fully covered.
        """
        all_starts = sorted({date.fromisoformat(sy["start"]) for sy in self.school_years})
        all_ends = sorted({date.fromisoformat(sy["end"]) for sy in self.school_years})
        if not all_starts:
            return []

        intervals = []
        # Start from May 22 two years before to capture pre-instruction gap days
        first_sy_start = all_starts[0]
        d = date(first_sy_start.year - 2, 5, 22)
        # End: latest of (last school year end, last break end date)
        # This ensures we cover the summer after the final school year
        all_break_ends = sorted({
            date.fromisoformat(br["end"])
            for sy in self.school_years
            for br in sy.get("breaks", {}).values()
        })
        all_nsd_ends = sorted({
            date.fromisoformat(nsd["date"])
            for sy in self.school_years
            for nsd in sy.get("noschool_days", [])
        })
        end_candidates = [all_ends[-1]] + (list(all_break_ends) if all_break_ends else []) + (list(all_nsd_ends) if all_nsd_ends else [])
        end_d = max(end_candidates)

        while d <= end_d:
            custodian, reason = self._get_custodian(d)
            if intervals and intervals[-1].custodian == custodian and intervals[-1].reason == reason:
                intervals[-1].end = d
            else:
                intervals.append(Interval(d, d, custodian, reason))
            d += timedelta(days=1)

        return intervals

    def save_intervals(self, intervals: list, output_path: str) -> None:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(
                {"count": len(intervals), "intervals": [iv.to_dict() for iv in intervals]},
                f, indent=2, ensure_ascii=False
            )
        print(f"[custody_calculator] Saved {len(intervals)} intervals to {output_path}")


def load_rules(path: str) -> dict:
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def load_standard_calendar(path: str) -> dict:
    with open(path, encoding="utf-8") as f:
        return json.load(f)


if __name__ == "__main__":
    rules = load_rules(sys.argv[1])
    cal = load_standard_calendar(sys.argv[2])
    calc = CustodyCalculator(rules, cal)
    intervals = calc.compute_intervals()
    print(f"Total intervals: {len(intervals)}")
